import { MigrationInterface, QueryRunner } from 'typeorm';

export class init1581161692552 implements MigrationInterface {
    name = 'init1581161692552'

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "dictionary" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, CONSTRAINT "UQ_81db3138fa4c73261359f4f99eb" UNIQUE ("title"), CONSTRAINT "PK_d17df343bd5d01ed62dd0e55e4a" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "dictionary_item" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "dictionary_id" integer NOT NULL, CONSTRAINT "PK_2fca955528c6e57d6c5a4eee00e" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "address" ("id" SERIAL NOT NULL, "country" character varying NOT NULL, "region" character varying NOT NULL, "locality" character varying NOT NULL, "street" character varying NOT NULL, "building" character varying NOT NULL, "longitude" double precision NOT NULL, "latitude" double precision NOT NULL, "locality_type_id" integer, CONSTRAINT "REL_bff9739bb80e6cb39bc4b71098" UNIQUE ("locality_type_id"), CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "description" ("id" SERIAL NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_313ee7159517cb494d532ee5466" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "university_id" integer, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "course_lector" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_6cb2805925ca7a95bc26b46b647" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "course" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description_id" integer, "university_id" integer NOT NULL, "lector_id" integer NOT NULL, CONSTRAINT "REL_de3e4362afce43cbd53ab01822" UNIQUE ("description_id"), CONSTRAINT "PK_bf95180dd756fd204fb01ce4916" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "university_address" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "university_id" integer, "address_id" integer NOT NULL, CONSTRAINT "REL_e35bf2d32bfca70e5acbb7c82e" UNIQUE ("address_id"), CONSTRAINT "PK_399283cb5b91ec6f239586d2d56" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "university" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description_id" integer NOT NULL, CONSTRAINT "REL_4b6e570d8dd89244c0eff17a72" UNIQUE ("description_id"), CONSTRAINT "PK_d14e5687dbd51fd7a915c22ac13" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "faculty_address" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "faculty_id" integer, "address_id" integer NOT NULL, CONSTRAINT "REL_92492453cf1349a54f8f0b7d1c" UNIQUE ("address_id"), CONSTRAINT "PK_a80573f2c4bfc6fdbc8a705950f" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "faculty" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "university_id" integer NOT NULL, "description_id" integer, CONSTRAINT "REL_37d8c68016e58cd3527bcac72a" UNIQUE ("description_id"), CONSTRAINT "PK_635ca3484f9c747b6635a494ad9" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "department_address" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "department_id" integer, "address_id" integer NOT NULL, CONSTRAINT "REL_4b34b6b1364daa0add0b7f57fd" UNIQUE ("address_id"), CONSTRAINT "PK_45550dad3c1560faad612e09ebf" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "department" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "faculty_id" integer NOT NULL, "description_id" integer, CONSTRAINT "REL_a7a3d061f326c8575b097e2617" UNIQUE ("description_id"), CONSTRAINT "PK_9a2213262c1593bffb581e382f5" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "specialty_address" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "specialty_id" integer, "address_id" integer NOT NULL, CONSTRAINT "REL_7d4524331dd1051a58c98f62c4" UNIQUE ("address_id"), CONSTRAINT "PK_7927bb753912184e14aeba2a86f" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "specialty" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "price" integer NOT NULL, "duration" integer NOT NULL, "department_id" integer, "description_id" integer, CONSTRAINT "REL_e9d191338bfd10326917241fc8" UNIQUE ("description_id"), CONSTRAINT "PK_9cf4ae334dc4a1ab1e08956460e" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "threshold_score" ("id" SERIAL NOT NULL, "value" integer NOT NULL DEFAULT '0', "competition_id" integer, "subject_id" integer NOT NULL, CONSTRAINT "REL_cb627df00324edf6cd3dae8b3f" UNIQUE ("subject_id"), CONSTRAINT "PK_c08ae5d87c5e5bbe3a61afdea15" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "competition" ("id" SERIAL NOT NULL, "enrollee" integer NOT NULL DEFAULT '0', "slots" integer NOT NULL DEFAULT '0', "start_date" date NOT NULL, "end_date" date NOT NULL, "specialty_id" integer NOT NULL, CONSTRAINT "PK_a52a6248db574777b226e9445bc" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "enrollee_reward" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "file_id" integer NOT NULL, "title" character varying(250) NOT NULL, "description" character varying(1000) NOT NULL, CONSTRAINT "PK_7981622f72f29463cbccdcc3ea6" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "enrollee_score" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "value" integer NOT NULL DEFAULT '0', "subject_id" integer NOT NULL, CONSTRAINT "REL_2042a4e247207cd3cec2a97727" UNIQUE ("subject_id"), CONSTRAINT "PK_aa5e8759298e4ff03e9c70cd1ee" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "privileged" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "privilege_id" integer NOT NULL, CONSTRAINT "REL_a8060d154c637013ffa94794aa" UNIQUE ("privilege_id"), CONSTRAINT "PK_63c88e928476553f3b00c11ff1b" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "semester" ("id" SERIAL NOT NULL, "year_number" integer NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "specialty_id" integer NOT NULL, CONSTRAINT "REL_1da2dbafc9477fa2d2abd0ee52" UNIQUE ("specialty_id"), CONSTRAINT "PK_9129c1fd35aa4aded7a9825b38d" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "specialty_teaching_type" ("specialty_id" integer NOT NULL, "teaching_type_id" integer NOT NULL, CONSTRAINT "PK_5f62072c41b8057191dd55a7ed6" PRIMARY KEY ("specialty_id", "teaching_type_id"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_93c102de9180a3687e60e15169" ON "specialty_teaching_type" ("specialty_id") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_e6e7a4ac1b8e2a213446211677" ON "specialty_teaching_type" ("teaching_type_id") `, undefined);
        await queryRunner.query(`CREATE TABLE "specialty_payment_type" ("specialty_id" integer NOT NULL, "payment_type_id" integer NOT NULL, CONSTRAINT "PK_ebe2ca4626c4481c3f6dcf9433c" PRIMARY KEY ("specialty_id", "payment_type_id"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_96c2d29f4a311171a1983a8b76" ON "specialty_payment_type" ("specialty_id") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_0ef7e1676b8fe4073e67477cc3" ON "specialty_payment_type" ("payment_type_id") `, undefined);
        await queryRunner.query(`CREATE TABLE "semester_course" ("semester_id" integer NOT NULL, "course_id" integer NOT NULL, CONSTRAINT "PK_95ac01bbf2cd57fd4780f449b45" PRIMARY KEY ("semester_id", "course_id"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_5fa03d0bfba0c1bbc16922d963" ON "semester_course" ("semester_id") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_254df6f0ab3a6de26752d0650c" ON "semester_course" ("course_id") `, undefined);
        await queryRunner.query(`ALTER TABLE "dictionary_item" ADD CONSTRAINT "FK_1608134a8953de13efe191dd36b" FOREIGN KEY ("dictionary_id") REFERENCES "dictionary"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_bff9739bb80e6cb39bc4b710983" FOREIGN KEY ("locality_type_id") REFERENCES "dictionary_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_db9eac8d609a4b6a6c30d4c8b53" FOREIGN KEY ("university_id") REFERENCES "university"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_de3e4362afce43cbd53ab018226" FOREIGN KEY ("description_id") REFERENCES "description"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_c4a012bebacccd486511a11d90b" FOREIGN KEY ("university_id") REFERENCES "university"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_6cb2805925ca7a95bc26b46b647" FOREIGN KEY ("lector_id") REFERENCES "course_lector"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "university_address" ADD CONSTRAINT "FK_951b931adca000d5130d033c30f" FOREIGN KEY ("university_id") REFERENCES "university"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "university_address" ADD CONSTRAINT "FK_e35bf2d32bfca70e5acbb7c82ea" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "university" ADD CONSTRAINT "FK_4b6e570d8dd89244c0eff17a721" FOREIGN KEY ("description_id") REFERENCES "description"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "faculty_address" ADD CONSTRAINT "FK_99f014c3173e4ca38004e2069c3" FOREIGN KEY ("faculty_id") REFERENCES "faculty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "faculty_address" ADD CONSTRAINT "FK_92492453cf1349a54f8f0b7d1c5" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "faculty" ADD CONSTRAINT "FK_dd143513e8e517ee17c0798d63b" FOREIGN KEY ("university_id") REFERENCES "university"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "faculty" ADD CONSTRAINT "FK_37d8c68016e58cd3527bcac72a1" FOREIGN KEY ("description_id") REFERENCES "description"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "department_address" ADD CONSTRAINT "FK_9bca9c7738728db436817e6d14b" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "department_address" ADD CONSTRAINT "FK_4b34b6b1364daa0add0b7f57fd9" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_0f481340d0ba8db6ca9307180cf" FOREIGN KEY ("faculty_id") REFERENCES "faculty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "FK_a7a3d061f326c8575b097e26171" FOREIGN KEY ("description_id") REFERENCES "description"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_address" ADD CONSTRAINT "FK_62647dc171616a9488670bc08d9" FOREIGN KEY ("specialty_id") REFERENCES "specialty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_address" ADD CONSTRAINT "FK_7d4524331dd1051a58c98f62c49" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty" ADD CONSTRAINT "FK_6fd4d1ff70d78becffb0b48120a" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty" ADD CONSTRAINT "FK_e9d191338bfd10326917241fc89" FOREIGN KEY ("description_id") REFERENCES "description"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "threshold_score" ADD CONSTRAINT "FK_0f8bc6dc77f9027973b543d8956" FOREIGN KEY ("competition_id") REFERENCES "competition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "threshold_score" ADD CONSTRAINT "FK_cb627df00324edf6cd3dae8b3f1" FOREIGN KEY ("subject_id") REFERENCES "dictionary_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "competition" ADD CONSTRAINT "FK_cd2cbcbeafe00c85488038c6a4d" FOREIGN KEY ("specialty_id") REFERENCES "specialty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "enrollee_score" ADD CONSTRAINT "FK_2042a4e247207cd3cec2a977272" FOREIGN KEY ("subject_id") REFERENCES "dictionary_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "privileged" ADD CONSTRAINT "FK_a8060d154c637013ffa94794aa9" FOREIGN KEY ("privilege_id") REFERENCES "dictionary_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "semester" ADD CONSTRAINT "FK_1da2dbafc9477fa2d2abd0ee526" FOREIGN KEY ("specialty_id") REFERENCES "specialty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_teaching_type" ADD CONSTRAINT "FK_93c102de9180a3687e60e15169e" FOREIGN KEY ("specialty_id") REFERENCES "specialty"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_teaching_type" ADD CONSTRAINT "FK_e6e7a4ac1b8e2a2134462116770" FOREIGN KEY ("teaching_type_id") REFERENCES "dictionary_item"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_payment_type" ADD CONSTRAINT "FK_96c2d29f4a311171a1983a8b76e" FOREIGN KEY ("specialty_id") REFERENCES "specialty"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_payment_type" ADD CONSTRAINT "FK_0ef7e1676b8fe4073e67477cc33" FOREIGN KEY ("payment_type_id") REFERENCES "dictionary_item"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "semester_course" ADD CONSTRAINT "FK_5fa03d0bfba0c1bbc16922d963a" FOREIGN KEY ("semester_id") REFERENCES "semester"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "semester_course" ADD CONSTRAINT "FK_254df6f0ab3a6de26752d0650c5" FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "semester_course" DROP CONSTRAINT "FK_254df6f0ab3a6de26752d0650c5"`, undefined);
        await queryRunner.query(`ALTER TABLE "semester_course" DROP CONSTRAINT "FK_5fa03d0bfba0c1bbc16922d963a"`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_payment_type" DROP CONSTRAINT "FK_0ef7e1676b8fe4073e67477cc33"`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_payment_type" DROP CONSTRAINT "FK_96c2d29f4a311171a1983a8b76e"`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_teaching_type" DROP CONSTRAINT "FK_e6e7a4ac1b8e2a2134462116770"`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_teaching_type" DROP CONSTRAINT "FK_93c102de9180a3687e60e15169e"`, undefined);
        await queryRunner.query(`ALTER TABLE "semester" DROP CONSTRAINT "FK_1da2dbafc9477fa2d2abd0ee526"`, undefined);
        await queryRunner.query(`ALTER TABLE "privileged" DROP CONSTRAINT "FK_a8060d154c637013ffa94794aa9"`, undefined);
        await queryRunner.query(`ALTER TABLE "enrollee_score" DROP CONSTRAINT "FK_2042a4e247207cd3cec2a977272"`, undefined);
        await queryRunner.query(`ALTER TABLE "competition" DROP CONSTRAINT "FK_cd2cbcbeafe00c85488038c6a4d"`, undefined);
        await queryRunner.query(`ALTER TABLE "threshold_score" DROP CONSTRAINT "FK_cb627df00324edf6cd3dae8b3f1"`, undefined);
        await queryRunner.query(`ALTER TABLE "threshold_score" DROP CONSTRAINT "FK_0f8bc6dc77f9027973b543d8956"`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty" DROP CONSTRAINT "FK_e9d191338bfd10326917241fc89"`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty" DROP CONSTRAINT "FK_6fd4d1ff70d78becffb0b48120a"`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_address" DROP CONSTRAINT "FK_7d4524331dd1051a58c98f62c49"`, undefined);
        await queryRunner.query(`ALTER TABLE "specialty_address" DROP CONSTRAINT "FK_62647dc171616a9488670bc08d9"`, undefined);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_a7a3d061f326c8575b097e26171"`, undefined);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "FK_0f481340d0ba8db6ca9307180cf"`, undefined);
        await queryRunner.query(`ALTER TABLE "department_address" DROP CONSTRAINT "FK_4b34b6b1364daa0add0b7f57fd9"`, undefined);
        await queryRunner.query(`ALTER TABLE "department_address" DROP CONSTRAINT "FK_9bca9c7738728db436817e6d14b"`, undefined);
        await queryRunner.query(`ALTER TABLE "faculty" DROP CONSTRAINT "FK_37d8c68016e58cd3527bcac72a1"`, undefined);
        await queryRunner.query(`ALTER TABLE "faculty" DROP CONSTRAINT "FK_dd143513e8e517ee17c0798d63b"`, undefined);
        await queryRunner.query(`ALTER TABLE "faculty_address" DROP CONSTRAINT "FK_92492453cf1349a54f8f0b7d1c5"`, undefined);
        await queryRunner.query(`ALTER TABLE "faculty_address" DROP CONSTRAINT "FK_99f014c3173e4ca38004e2069c3"`, undefined);
        await queryRunner.query(`ALTER TABLE "university" DROP CONSTRAINT "FK_4b6e570d8dd89244c0eff17a721"`, undefined);
        await queryRunner.query(`ALTER TABLE "university_address" DROP CONSTRAINT "FK_e35bf2d32bfca70e5acbb7c82ea"`, undefined);
        await queryRunner.query(`ALTER TABLE "university_address" DROP CONSTRAINT "FK_951b931adca000d5130d033c30f"`, undefined);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_6cb2805925ca7a95bc26b46b647"`, undefined);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_c4a012bebacccd486511a11d90b"`, undefined);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_de3e4362afce43cbd53ab018226"`, undefined);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_db9eac8d609a4b6a6c30d4c8b53"`, undefined);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_bff9739bb80e6cb39bc4b710983"`, undefined);
        await queryRunner.query(`ALTER TABLE "dictionary_item" DROP CONSTRAINT "FK_1608134a8953de13efe191dd36b"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_254df6f0ab3a6de26752d0650c"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_5fa03d0bfba0c1bbc16922d963"`, undefined);
        await queryRunner.query(`DROP TABLE "semester_course"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_0ef7e1676b8fe4073e67477cc3"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_96c2d29f4a311171a1983a8b76"`, undefined);
        await queryRunner.query(`DROP TABLE "specialty_payment_type"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_e6e7a4ac1b8e2a213446211677"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_93c102de9180a3687e60e15169"`, undefined);
        await queryRunner.query(`DROP TABLE "specialty_teaching_type"`, undefined);
        await queryRunner.query(`DROP TABLE "semester"`, undefined);
        await queryRunner.query(`DROP TABLE "privileged"`, undefined);
        await queryRunner.query(`DROP TABLE "enrollee_score"`, undefined);
        await queryRunner.query(`DROP TABLE "enrollee_reward"`, undefined);
        await queryRunner.query(`DROP TABLE "competition"`, undefined);
        await queryRunner.query(`DROP TABLE "threshold_score"`, undefined);
        await queryRunner.query(`DROP TABLE "specialty"`, undefined);
        await queryRunner.query(`DROP TABLE "specialty_address"`, undefined);
        await queryRunner.query(`DROP TABLE "department"`, undefined);
        await queryRunner.query(`DROP TABLE "department_address"`, undefined);
        await queryRunner.query(`DROP TABLE "faculty"`, undefined);
        await queryRunner.query(`DROP TABLE "faculty_address"`, undefined);
        await queryRunner.query(`DROP TABLE "university"`, undefined);
        await queryRunner.query(`DROP TABLE "university_address"`, undefined);
        await queryRunner.query(`DROP TABLE "course"`, undefined);
        await queryRunner.query(`DROP TABLE "course_lector"`, undefined);
        await queryRunner.query(`DROP TABLE "role"`, undefined);
        await queryRunner.query(`DROP TABLE "description"`, undefined);
        await queryRunner.query(`DROP TABLE "address"`, undefined);
        await queryRunner.query(`DROP TABLE "dictionary_item"`, undefined);
        await queryRunner.query(`DROP TABLE "dictionary"`, undefined);
    }

}
